Implemented indexing packages in staging area

diff --git a/system/apps/utils/Builder/bin/build b/system/apps/utils/Builder/bin/build
--- a/system/apps/utils/Builder/bin/build
+++ b/system/apps/utils/Builder/bin/build
@@ -1,7 +1,7 @@
 #!/usr/bin/env ruby
 
 # Syllable Build System
-# Version 0.5.65
+# Version 0.5.66
 # Copyright (c) 2002-2005 Kaj de Vos
 # License: GPL 2
 
@@ -438,9 +438,11 @@ def installPackage staging, target
 					then
 						false
 					else
-						@systemBuild or staging or
-						begin
-							@log.header 'Registering ' + target
+						@log.header 'Registering ' + target
+
+						if @systemBuild or staging
+							registerPackage staging, target
+						else
 							action 'pkgmanager --add ' + root
 						end
 					end
@@ -516,6 +518,46 @@ def makeDistroPackage target
 				@log.failure target
 			else
 				action 'sync'
+			end
+		end
+	end
+end
+
+def registerPackage staging, target  # Create symlinks for a ported package
+#	@log.header 'Registering ' + target
+
+	unless
+		for subdir in ['etc', 'bin', 'sbin', 'info']  # Flat directories
+			break unless linkSubdir staging, target, subdir, false
+		end and
+		for subdir in ['lib', 'libexec', 'include', 'share'] << 'man'  # Nested directories
+			break unless linkSubdir staging, target, subdir, true
+		end
+	then
+#		@log.failure target
+		false
+	else
+		action 'sync'
+	end
+end
+
+def linkSubdir staging, target, subdir, nest
+	not exists? dir = File.join(installPath(staging, target), subdir) or
+	begin
+		@log.detail subdir
+		Dir.chdir dir
+
+		Dir[nest ? '**/*' : '*'].each do |node|
+			destination = File.join(@indexesRoot, subdir, node)
+
+			if dir? node
+#				@log.detail subdir
+				return false unless dir? destination or action 'mkdir ' + destination
+			elsif symlink? destination
+				@log.error "Conflict: link to file #{node} already exists!"
+				return false
+			else
+				File.symlink File.join(installPath(false, target), subdir, node), destination
 			end
 		end
 	end
@@ -860,8 +902,12 @@ def dir? file
 	FileTest.directory? file
 end
 
+def symlink? file
+	FileTest.symlink? file
+end
+
 def dereference file
-	FileTest.symlink?(file) ?
+	symlink?(file) ?
 		(file[0, 1] == '/' ?
 			('/' + dereference(File.readlink(file))) :
 			dereference(File.readlink(file))
@@ -988,11 +1034,11 @@ def prefix package
 end
 
 def installRoot staging
+	! staging ?
+		'/usr' :
 	@systemBuild ?
 		File.join(@systemRoot, 'usr') :
-	staging ?
-		@stage :
-		'/usr'
+		@stage
 end
 
 def installPath staging, package
@@ -1225,6 +1271,8 @@ else
 	ENV['DIST_DIR'] = @stage
 end
 
+@indexesRoot = File.join @systemImage, 'atheos/autolnk'
+
 # Set environment variables
 
 for line in parseList @settings['environment']
@@ -1239,7 +1287,7 @@ arg1, arg2, arg3 = ARGV
 
 case arg1
 when '-v', '--version'
-	puts 'Syllable Build System 0.5.65',
+	puts 'Syllable Build System 0.5.66',
 		'Copyright (c) 2002-2005 Kaj de Vos',
 		'License: GPL 2'
 when '?', '-?', '-h', '-help', '--help'
@@ -1386,7 +1434,7 @@ else
 			else
 				if arg2
 					@log.error 'Unrecognized command'
-					exit
+					exit 1
 				else
 					build false, target
 				end
@@ -1403,5 +1451,6 @@ else
 
 	action 'sync'
 	@log.close
+	exit @log.failures.length  # FIXME: only works when processing a profile
 end
 
